---
title: "Analysis Notebook"
output: github_document
editor_options: 
  chunk_output_type: inline
---

```{r Load library}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(rstatix))
```

```{r Load Data}
#Les_diffe_rents_accents_du_franc_ais_Asians_Whites_October_26_2022_08_24 <- read_excel("Data/Les différents accents du français - Asians+Whites_October 26, 2022_08.24.xlsx")
raw_data <- Les_diffe_rents_accents_du_franc_ais_Asians_Whites_October_26_2022_08_24


print(raw_data[1,])
```


```{r Rename Columns}
data <- raw_data[-1, ]

data <- data %>%
  select(-c(IPAddress, Finished, ResponseId, QID18_1, QID18_2, QID18_3,
            QID18_5, QID18_6, QID18_7, QID18_8, QID18_9, QID18_10, QID19, `10B`, Courriel,
            `1B`, `2B`, `3B`, `4B`, `5B`, `6B`, `7B`, `8B`, `9B`, `10B`)) %>% 
  rename(gender = Q1,
         gender_other = Q1_4_TEXT, 
         age = Q2,
         country_of_birth = Q3,
         grow_up_province = Q41,
         grow_up_city = Q4,
         field_of_study = Q5,
         ethnic_group = Q6,
         ethnic_group_other = Q6_13_TEXT, 
         num_of_language = Q7...123, 
         spoken_language = Q7...124, 
         spoken_language_other = Q7_11_TEXT,
         mother_tongue = Q8,
         mother_tongue_other = Q8_11_TEXT,
         year_of_french = Q9,
         french_speaking_place = Q10,
         french_speaking_place_other = Q10_6_TEXT,
         month_live_in_fr_env = Q10B,
         pref_french = Q11,
         pref_french_other = Q11_3_TEXT,
         teacher_origin = Q12, 
         teacher_origin_other = Q12_3_TEXT
         ) %>% 
  mutate(age = as.numeric(age),
         num_of_language = as.numeric(num_of_language),
         year_of_french = as.numeric(year_of_french),
         )

# convert rating 
data <- data %>%  
  mutate_at(vars(1:90), as.numeric)

data <- data %>% 
  mutate_if(is.character, as.factor)
```


# Participant Portrait

```{r}
nrow(data)
```


```{r Participant gender}
data %>% 
  group_by(gender) %>% 
  tally() %>%  
  mutate(prop = scales::percent(n/nrow(data)))


data %>%  
  select(gender, gender_other) %>% 
  filter(gender %in% c('Prefer not to answer', 'Prefer to define myself', NA))
# 1 person recognize as agnder, others did not reveal 
```

```{r Participant Age}
range(data$age, na.rm = TRUE)

# 9 missing value  
data %>%  
  ggplot(aes(x = age)) + 
  geom_density() + 
  geom_vline(xintercept = mean(data$age, na.rm = TRUE), color = 'red') + 
  theme_bw()
```

```{r Country of Birth}
# born in Canda
data %>%  
  select(country_of_birth) %>%  
  mutate(Canada = ifelse(country_of_birth == 'Canada', TRUE, FALSE)) %>% 
  group_by(Canada) %>% 
  tally()


data %>%  
  drop_na(country_of_birth) %>% 
  select(country_of_birth) %>% 
  filter(country_of_birth != 'Canada') %>% 
  mutate(continent = case_when(country_of_birth %in% c('China', 'India', 'South Korea', 'Japan', 'Pakistan', 'Philippines') ~ 'Asia', 
                               country_of_birth %in% c('Mauritius', 'Egypt', 'Nigeria') ~ 'Africa',
                               country_of_birth %in% c('United Kingdom of Great Britain and Northern Ireland', 'Czech Republic', 'Italy', 'Germany') ~ 'Europe',
                               country_of_birth %in% c('United States of America', 'Brazil', 'Mexico') ~ 'America')) %>%  
  group_by(continent) %>%  
  tally()
```

```{r Grow-up Province}
data %>% 
  filter(country_of_birth == 'Canada') %>%  
  group_by(grow_up_province) %>% 
  tally() %>% 
  mutate(prop = scales::percent(n/sum(n)))
```

```{r Field of Study}
data %>%  
  group_by(field_of_study) %>% 
  tally() %>% 
  filter(field_of_study %in% c('Français', 'French', 'Linguistic', 'linguistique et psychologie', 'linguistiques', 'Linguistiques (Arts)'))
# six people are with French or linguitistic background
```
```{r ethnic group}
data %>% 
  group_by(ethnic_group) %>% 
  tally()
```




```{r # of Language Spoken}
# 13 missing data 
data %>% 
  # drop_na(num_of_language) %>% 
  group_by(num_of_language) %>% 
  tally() %>% 
  mutate(prop = scales::percent(n/sum(n))) 
```


```{r Spoken Language}
# 7 missing values 
data %>% 
  drop_na(spoken_language) %>% 
  select(spoken_language, spoken_language_other) %>% 
  mutate(English = ifelse(str_detect(spoken_language, 'English'), TRUE, FALSE)) %>% 
  filter(English != TRUE)
# 2 people don't speak English 
```

```{r Month Tongue}
month_tongue_df <- data %>% 
  select(mother_tongue) %>%
  mutate(English = ifelse(str_detect(mother_tongue, "English") | str_detect(mother_tongue, "Anglais"), TRUE, FALSE),
         Cantonese = ifelse(str_detect(mother_tongue,"Cantonese"), TRUE, FALSE), 
         Hindi = ifelse(str_detect(mother_tongue,"Hindi"), TRUE, FALSE),
         Mandarin = ifelse(str_detect(mother_tongue,"Mandarin"), TRUE, FALSE),      
         Korean = ifelse(str_detect(mother_tongue,"Korean"), TRUE, FALSE),
         Spanish = ifelse(str_detect(mother_tongue,"Spanish"), TRUE, FALSE),  
         German = ifelse(str_detect(mother_tongue,"German"), TRUE, FALSE),  
         Tagalog = ifelse(str_detect(mother_tongue,"Tagalog"), TRUE, FALSE))  

language_count = matrix(NA, nrow = 7, ncol = 2)
language_count[,1] <- names(month_tongue_df)[2:8]
for (i in 1:7){
  language_count[i,2] = as.numeric(table(month_tongue_df[,i+1]))[2]
}


language_count <- as.data.frame(language_count)
colnames(language_count) = c('mother_tongue', 'n')

language_count %>% arrange(desc(n))
```

```{r Year of Studying French}

# 15 missing value
data %>% 
  # drop_na(year_of_french) %>% 
  mutate(year_interval = case_when(year_of_french<=5~'0-5', 
                                   year_of_french>5 & year_of_french <= 10~ '5-10', 
                                   year_of_french>10 & year_of_french<= 15~ '10-15', 
                                   year_of_french > 15~'15+')) %>% 
  group_by(year_interval) %>%
  tally() %>% 
  mutate(prop = scales::percent(n/sum(n)))

  
  
  
  # drop_
  # tally() %>% 
  # ggplot(aes(x="", y = n, fill=year_group))+
  # geom_bar(width = 1, stat = "identity")+
  # coord_polar("y") + 
  # scale_fill_discrete(name = "Years of Studying French") 
```



```{r Live in French-speaking Area }
live_in_french_env_df <- as.data.frame(t(as.data.frame(data %>% 
  select(french_speaking_place)  %>% 
  group_by(french_speaking_place) %>% 
  tally() %>% 
  mutate(France = ifelse(french_speaking_place == 'France' | french_speaking_place == 'France, Elsewhere? if so please specify:', n, NA),
         Quebec = ifelse(french_speaking_place == 'Quebec' | french_speaking_place == 'Quebec, Elsewhere? if so please specify:', n, NA),
         never = ifelse(str_detect(french_speaking_place, 'I have never stayed in a French-speaking context.'), n, NA),
         other = ifelse(french_speaking_place == 'Elsewhere? if so please specify:', n, NA),
         both = ifelse(french_speaking_place %in% c('Quebec and France', 'Quebec, France'), n, NA),
         unkown = ifelse(is.na(french_speaking_place), n, NA)
         )%>% 
  summarize(France = sum(France, na.rm = TRUE),
            Quebec = sum(Quebec, na.rm = TRUE),
            never = sum(never, na.rm = TRUE),
            other = sum(other, na.rm = TRUE),
            both = sum(both, na.rm = TRUE), 
            unkown = sum(unkown, na.rm = TRUE)))))

live_in_french_env_df <- tibble::rownames_to_column(live_in_french_env_df, "Area")
live_in_french_env_df %>% 
  mutate(prop = scales::percent(V1/sum(V1)))
```
```{r Months of Living in French-speaking areas}
levels(data$month_live_in_fr_env) <- c("1 - 3", "4 - 6", "7 - 12", "< 1", "> 12")
data$month_live_in_fr_env <- factor(data$month_live_in_fr_env, levels = c("< 1", "1 - 3", "4 - 6", "7 - 12", "> 12")) 
data %>% 
  group_by(month_live_in_fr_env) %>% 
  tally() %>%  
  mutate(prop = scales::percent(n/sum(n))) 
```

```{r Preferred Type of French}
data %>% 
  select(pref_french) %>% 
  group_by(pref_french) %>%
  tally() %>% 
  mutate(prop = scales::percent(n/sum(n)))

```


```{r Origin of Teacher}
data %>% 
  group_by(teacher_origin) %>%  
  tally() 

data %>%  
  filter(teacher_origin == 'Other(s), specify:') %>% 
  select(teacher_origin_other)
```


# Part I - Recording Evaluation

1A: Quebec. White.
2A: French. White
3A. Acadian. White
4A. English. White.
5A. African. White.
6A. Quebec. Asian
7A. African. Asian
8A. Acadian. Asian
9A. French. Asian
10A. English. Asian



```{r}

```



```{r }
names(data)
```

#
















